Symfony\Component\Debug\Exception\FlattenException:
    exclusion_policy: ALL
    read_only: true
    access_type: public_method
    # discriminator:
    #     field_name: class
    #     map:
    #         Matmar10\\Bundle\\RestApiBundle\\Exception\\ConstraintViolationException: Matmar10\\Bundle\\RestApiBundle\\Entity\\ConstraintViolationListException
    properties:
        message:
            type: string
            groups: [all]
        code:
            type: integer
            groups: [all]
        trace:
            type: array
            groups: [all, debug]
        class:
            type: string
            groups: [all, debug]
        file:
            type: string
            groups: [all, debug]
        line:
            type: integer
            groups: [all, debug]


