jms_serializer:
    metadata:
        directories:
            symfony_component:
               namespace_prefix: "Symfony\\Component"
               path: "@Matmar10RestApiBundle/Resources/config/serializer/Symfony.Component"
            rest_api_entities:
                namespace_prefix: "Matmar10\\Bundle\\RestApiBundle\\Entity"
                path: "@Matmar10RestApiBundle/Resources/config/serializer/Matmar10.Bundle.RestApiBundle.Entity"
