jms_serializer:
    metadata:
        directories:
            SymfonyExceptions:
                namespace_prefix: "Symfony\\Component\\Debug\\Exception"
                path: "@Matmar10RestApiBundle/Resources/config/serializer"
            RestApiExceptions:
                namespace_prefix: "Matmar10\\Bundle\\RestApiBundle\\Entity"
                path: "@Matmar10RestApiBundle/Resources/config/serializer"
