
Matmar10\Bundle\RestApiBundle\Entity\ConstraintViolationListException:
    exclusion_policy: NONE
    read_only: true
    access_type: public_method
    properties:
        constraintViolations:
            groups: [all, debug]
            read_only: true
            serialized_name: constraintViolations
            # see: https://github.com/matmar10/rest-api-bundle/issues/6
            # type: array<Symfony\Component\Validator\ConstraintViolation>
            type: array<Matmar10\Bundle\RestApiBundle\Entity\ConstraintViolation>
